### ISSUE TITLE
C2 attribute level tags needed

### ISSUE THREAD

**Issue by jaegeral** [DCSO/tie2misp#11]
On an attribute level it would be also valuable to have tags like:
````
PAP:GREEN
veris:action:malware:variety="C2"
veris:confidence="High"
tlp:amber
````

Depending on the content of course.

**Comment by Mezzonian** [comment]
I had some problems to implement tagging, but I'll see if I can fix it in the next update.

**Comment by jaegeral** [comment]
do you have an ETA for that?

**Comment by Mezzonian** [comment]
I was on vacation for the last two weeks and I hope to have some time in the next week to make a few things for tie2misp. On my local branch, the tags works allready fine.

**Comment by Mezzonian** [comment]
On my local branch, tagging of events works fine now. Tagging on attribute level works also but I don't recommend it, because if you want to tag an attribute you can't simple do it after adding the attribute to an event. The function MISP.add_attribute() from PyMISP returns not the added attribute with the corresponding uuid but rather returns the whole event with all attributes it has. So the parser have to run through all attributes to find the right one for tagging. If you have events with a lot of attributes, this could increase the runtime noticeable. To prevent this, I added a setting in the config file to disable tagging on attribute level.
